version: '3'
services:
  db:
    image: postgres
    container_name: stock_db
    environment:
      - POSTGRES_DB=stock
      - POSTGRES_USER=stock
      - POSTGRES_PASSWORD=stock
    ports:
      - "5433:5432"
